const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const schema = new Schema({
    so_number: { type: String, required: true },
    order_name: { type: String, required: true },
    current_status: { type: String, required: false, default: false },
    created_at: { type: Date, required: false, default: Date.now},
    updated_at: { type: Date, required: false, default: Date.now},
    customer_name: { type: String, required: true },
   	customer_contact: { type: String, required: true },
   	customer_email: { type: String, required: true },
   	customer_note: { type: String, required: false, default: ""},
    items: { type: Array, required: true, default: []},
    discount_code: {type: String, required: false},
    discount_amount: {type: Number, required: false, default: 0},
    total: {type: Number, required: true},
    total_tax: {type: Number, required: true},
    address: {type: String, required: true},
    city: {type: String, required: true},
    cost: {type: Number, required: false, default: 0},
    responsibility: {type: String, required: true, default:""},
    fulfillment_status: {type: String, required: false, default: ""},
    cancelled_reason: {type: String, required: false, default: ""},
    advance_payments: {type: Array, required: false, default: []},
    currency: {type: String, required: false, default: "USD"},
    pending_payment: {type: Number, required: false, default: 0},
    po_numbers: {type: Array, required: false, default: []},
    vendors: {type: Array, required: false, default: []},
    customizations: {type: Array, required: false, default: []},
    manufacturing_status: {type: String, required: false, default: ""},
    manufacturing_timeline: {type: String, required: false, default: ""},
    quality_approved: {type: String, required: false, default: ""},
    quality_reason: {type: String, required: false, default: ""},
    shipment_booking: {type: Boolean, required: false, default: false},
    shipment_booking_date: {type: Date, required: false, default: ""},
    booking_date: {type: Date, required: false, default: ""},
    shipment_mode: {type: String, required: false, default: ""},
    delivery_status: {type: Number, required: false, default: 0},
    freight_charges: {type: Number, required: false, default: 0},
    expected_delivery_date: {type: Date, required: false, default:""},
    delivery_date: {type: Date, required: false, default: ""},
    delivery_duration: {type: Number, required: false, default: 0},
    feedback: {type: String, required: false, default: ""},
    score: {type: Number, required: false, default: 0},
    order_again: {type: Boolean, required: false, default: null},
    complaint: {type: Boolean, required: false, default: null},
    complaint_date: {type: Date, required: false, default: ""},
    complaint_detail: {type: String, required: false, default: ""},
    complaint_resolution: {type: String, required: false, default: ""},
    complaint_resolution_date: {type: Date, required: false},
    complaint_resolution_time: {type: Number, required: false, default:0},
    follow_up_call: {type: Boolean, required: false, default: null},
    follow_up_call_progress: {type: Array, required: false, default:[]}
});

schema.set('toJSON', { virtuals: true });
module.exports = mongoose.model('order', schema);